### PR TITLE
Guess you took wrong name of property here

### PR DESCRIPTION
**Pull request by donalddaisy**
Please check and add to your next release version

### CODE REVIEW

**Comment by tmortagne** [comment]
Yeah the default format is what I use myself and forgot to actually test a different one...

**Comment by tmortagne** [comment]
Do you have an id on http://jira.xwiki.org so that I can assign https://jira.xwiki.org/browse/OIDC-44 to you ?

**Comment by donalddaisy** [comment]
I just created a new account tmeyer to stay in touch.

I'm afraid I'm not used to collaborating this way. What does "assign to you" mean in this context?

**Comment by tmortagne** [comment]
> I'm afraid I'm not used to collaborating this way

We usually try to keep jira and github in sync since we use jira to generate the changelog.

> What does "assign to you" mean in this context?

Just being credited for the fix and appear in jira's stats :)

**Comment by tmortagne** [comment]
Release done.

**Pull request merged**
